import { MenuItem } from "@/types";

export const MENU_ITEMS: MenuItem[] = [
  // DÖNERLER KATEGORİSİ
  {
    id: 1,
    name: "Et Döner",
    desc: "Özel marine edilmiş dana eti, taze sebzeler ve geleneksel soslar ile hazırlanmış.",
    price: "110₺",
    img: "/categories/menu/et-durum.webp",
    category: "Dönerler",
    ingredients: ["TerbiyeliDana eti", "Çıtır Patates", "Lavaş", "Domates", "Salatalık Turşusu", "Marul", "Özel Hatay sosu"],
  },
  {
    id: 2,
    name: "Tavuk Döner",
    desc: "Özel baharatlı tavuk eti, çıtır lavaş, bol yeşillik ve Hatay usulü sos.",
    price: "95₺",
    img: "/categories/menu/et-durum.webp",
    category: "Dönerler",
    ingredients: ["Terbiyeli Tavuk eti", "Çıtır Patates", "Lavaş", "Domates", "Salatalık Turşusu", "Marul", " Özel Hatay sosu", "Mayonez"],
  },
  {
    id: 3,
    name: "Mix Döner",
    desc: "Et ve tavuk karışımı, özel soslar ile harmanlanmış lezzetli döner.",
    price: "105₺",
    img: "/categories/menu/et-durum.webp",
    category: "Dönerler",
    ingredients: ["Terbiyeli Dana eti", "Çıtır Patates", "Terbiyeli Tavuk eti", "Lavaş", "Domates", "Salatalık Turşusu", "Marul", "Özel Hatay sosu", "Mayonez"],
  },
  {
    id: 4,
    name: "Köfte Döner",
    desc: "Ev yapımı köfte, taze sebzeler ve özel soslar ile hazırlanmış döner.",
    price: "100₺",
    img: "/categories/menu/et-durum.webp",
    category: "Dönerler",
    ingredients: ["Ev yapımı köfte", "Çıtır Patates", "Lavaş", "Domates", "Salatalık Turşusu", "Marul", "Özel Hatay sosu"],
  },
  {
    id: 5,
    name: "Zurna Et Döner",
    desc: "Dana eti, özel baharatlarla marine edilmiş, zurna şeklinde sarılmış lezzetli döner.",
    price: "115₺",
    img: "/categories/menu/zurna-doner.webp",
    category: "Dönerler",
    ingredients: ["Terbiyeli Dana eti", "Çıtır Patates", "Zurna ekmeği", "Domates", "Salatalık Turşusu", "Marul", "Özel Hatay sosu"],
  },
  {
    id: 6,
    name: "Zurna Tavuk Döner",
    desc: "Tavuk eti, özel baharatlarla marine edilmiş, zurna şeklinde sarılmış lezzetli döner.",
    price: "100₺",
    img: "/categories/menu/zurna-doner.webp",
    category: "Dönerler",
    ingredients: ["Terbiyeli Tavuk eti", "Çıtır Patates", "Zurna ekmeği", "Domates", "Salatalık Turşusu", "Marul", "Özel Hatay sosu", "Mayonez"],
  },
  {
    id: 7,
    name: "Zurna Mix Döner",
    desc: "Et ve tavuk karışımı, özel soslar ile harmanlanmış, zurna şeklinde sarılmış lezzetli döner.",
    price: "110₺",
    img: "/categories/menu/zurna-doner.webp",
    category: "Dönerler",
    ingredients: ["Terbiyeli Dana eti", "Çıtır Patates", "Terbiyeli Tavuk eti", "Zurna ekmeği", "Domates", "Salatalık Turşusu", "Marul", "Özel Hatay sosu", "Mayonez"],
  },

  // SERVİSLER KATEGORİSİ
  {
    id: 9,
    name: "Et Döner Porsiyon",
    desc: "Dana eti döner, salata ve özel soslar ile servis edilir.",
    price: "140₺",
    img: "/categories/menu/et-porsiyon.webp",
    category: "Servisler",
    ingredients: ["Terbiyeli Dana Eti ", "Çıtır Patates", "Domates", "Salatalık Turşusu", "Özel Hatay sosu", "Özel Hatay Lavaşı"],
  },
  {
    id: 10,
    name: "Tavuk Döner Porsiyon",
    desc: "Tavuk eti döner, salata ve özel soslar ile servis edilir.",
    price: "125₺",
    img: "/categories/menu/tavuk-porsiyon.webp",
    category: "Servisler",
    ingredients: ["Terbiyeli Tavuk Eti ", "Domates", "Salatalık Turşusu", "Çıtır Patates", "Özel Hatay sosu", "Özel Hatay Lavaşı"],
  },
  {
    id: 11,
    name: "Mix Porsiyon",
    desc: "Et ve tavuk karışımı döner, salata ve özel soslar ile servis edilir.",
    price: "135₺",
    img: "/categories/menu/mix-porsiyon.webp",
    category: "Servisler",
    ingredients: ["Terbiyeli Dana Eti", "Çıtır Patates", "Terbiyeli Tavuk Eti", "Domates", "Salatalık Turşusu", "Özel Hatay sosu", "Özel Hatay Lavaşı"],
  },
  {
    id: 12,
    name: "Köfte Porsiyon",
    desc: "Ev yapımı köfte, salata ve özel soslar ile hazırlanmış.",
    price: "130₺",
    img: "/categories/menu/köfte-porsiyon.webp",
    category: "Servisler",
    ingredients: ["Hatay Usulü Köfte", "Domates", "Salatalık Turşusu", "Çıtır Patates", "Özel Hatay Lavaşı"],
  },
  {
    id: 13,
    name: "Tavuk İskender",
    desc: "Geleneksel Tavuk İskender, yoğurt, domates sosu ve tereyağı ile.",
    price: "145₺",
    img: "/categories/menu/tavuk-porsiyon.webp",
    category: "Servisler",
    ingredients: ["Terbiyeli Tavuk Eti", "Yoğurt", "Özel Hatay Sosu", "Tereyağı", "İskender Ekmeği"],
  },
  {
    id: 14,
    name: "Et İskender",
    desc: "Geleneksel Et İskender, yoğurt, domates sosu ve tereyağı ile.",
    price: "160₺",
    img: "/categories/menu/et-porsiyon.webp",
    category: "Servisler",
    ingredients: ["Terbiyeli Dana Eti", "Yoğurt", "Özel Hatay Sosu", "Tereyağı", "İskender Ekmeği"],
  },
  {
    id: 15,
    name: "Tavuk Az Kes",
    desc: "Tavuk eti döner, salata ve özel soslar ile servis edilir.",
    price: "160₺",
    img: "/categories/menu/az-kes.webp",
    category: "Servisler",
    ingredients: ["Terbiyeli Tavuk Eti ", "Domates", "Salatalık Turşusu", "Çıtır Patates", "Özel Hatay sosu", "Özel Hatay Lavaşı"],
  },
  {
    id: 16,
    name: "Et Az Kes",
    desc: "Dana eti döner, salata ve özel soslar ile servis edilir.",
    price: "160₺",
    img: "/categories/menu/et-servis.webp",
    category: "Servisler",
    ingredients: ["Terbiyeli Dana Eti ", "Çıtır Patates", "Domates", "Salatalık Turşusu", "Özel Hatay sosu", "Özel Hatay Lavaşı"],
  },
  {
    id: 17,
    name: "Pilav Üstü Tavuk Döner",
    desc: "Terbiyeli tavuk eti, pilav ve salata ile servis edilir.",
    price: "160₺",
    img: "/categories/menu/az-kes.webp",
    category: "Servisler",
    ingredients: ["Terbiyeli Tavuk Eti ", "Pilav", "Domates", "Salatalık Turşusu", "Özel Hatay Lavaşı"],
  },
  {
    id: 18,
    name: "Pilav Üstü Et Döner",
    desc: "Terbiyeli dana eti, pilav ve salata ile servis edilir.",
    price: "160₺",
    img: "/categories/menu/et-servis.webp",
    category: "Servisler",
    ingredients: ["Terbiyeli Dana Eti ", "Pilav", "Domates", "Salatalık Turşusu", "Özel Hatay Lavaşı"],
  },

  // BURGERLER KATEGORİSİ
  {
    id: 19,
    name: "Tavuk Burger",
    desc: "Tavuk göğsü, taze sebzeler, özel sos ve çıtır ekmek ile hazırlanmış burger.",
    price: "85₺",
    img: "/categories/menu/tavuk-burger.webp",
    category: "Burgerler",
    ingredients: ["Terbiyeli Tavuk Eti", "Çıtır Burger", "Domates", "Salatalık Turşusu", "Çıtır Patates", "Marul", "Ketçap", "Mayonez"],
  },
  {
    id: 20,
    name: "Et Burger",
    desc: "Dana eti köftesi, taze sebzeler, özel sos ve çıtır ekmek ile hazırlanmış burger.",
    price: "95₺",
    img: "/categories/menu/et-burger.webp",
    category: "Burgerler",
    ingredients: ["Terbiyeli Dana Eti", "Çıtır Burger", "Çıtır Patates", "Domates", "Salatalık Turşusu", "Ketçap", "Mayonez"],
  },
  {
    id: 21,
    name: "Mix Burger",
    desc: "Et ve tavuk karışımı köfte, taze sebzeler, özel sos ve çıtır ekmek ile hazırlanmış burger.",
    price: "90₺",
    img: "/categories/menu/köfte-burger.webp",
    category: "Burgerler",
    ingredients: ["Terbiyeli Dana Eti", "Terbiyeli Tavuk Eti", "Çıtır Patates", "Çıtır Burger", "Domates", "Salatalık Turşusu", "Marul", "Ketçap", "Mayonez"],
  },
  {
    id: 22,
    name: "Ekmek Arası Köfte",
    desc: "Ev yapımı köfte, taze sebzeler ve özel soslar ile hazırlanmış ekmek arası.",
    price: "75₺",
    img: "/categories/menu/köfte-burger.webp",
    category: "Burgerler",
    ingredients: ["Hatay Usulü Köfte", "Çıtır Burger", "Domates", "Salatalık Turşusu", "Özel sos", "Çıtır Patates"],
  },

  // ATIŞTIRMALIKLAR KATEGORİSİ
  {
    id: 23,
    name: "Patates Kızartması",
    desc: "Çıtır çıtır patates kızartması, özel baharatlarla hazırlanmış.",
    price: "35₺",
    img: "/categories/menu/patates.webp",
    category: "Atıştırmalıklar",
    ingredients: ["Patates", "Zeytinyağı", "Tuz", "Özel baharatlar"],
  },

  // İÇECEKLER KATEGORİSİ
  {
    id: 24,
    name: "Ayran",
    desc: "Doğal ve serinletici ayran.",
    price: "20₺",
    img: "/categories/menu/ayran.webp",
    category: "İçecekler",
    ingredients: [],
  },
  {
    id: 25,
    name: "Kola",
    desc: "Buz gibi kola.",
    price: "25₺",
    img: "/categories/menu/kola.webp",
    category: "İçecekler",
    ingredients: [],
  },
  {
    id: 26,
    name: "Fuse Tea Çeşitleri",
    desc: "Şeftali, limon vb. ferahlatıcı soğuk çay seçenekleri.",
    price: "25₺",
    img: "/categories/menu/fuse-tea-cesitleri.webp",
    category: "İçecekler",
    ingredients: [],
  },
];
